let head = document.querySelector(".first");

let className = document.querySelector("h4");


/*elements can be accessed in three ways.
1. getElementById
2. getElementsByClassName
3. getElementByTag
*/

/*
document object has another class querySelector

1. querySelector(tag or class or id)
Anything can be given inside the brackets.
it does the starting element or tag that appears 

2. querySelectorAll(tag or class or id).
*/

/*
1. tagName --- it returns the tagname of the element Nodes.
2. innerText --- it returns the text content of the element and all of it's children.
3. innerHtml --- returns the plaintext or html content in the element.
4. textContent --- returns textual content even for the hidden elements.


*/









